### ISSUE TITLE
Please describe the Dropwizard vision for future place of Metrics library in Java world.

### ISSUE THREAD

**Issue by vladimir-bukhtoyarov** [marshallpierce/metrics-thoughts#1]
It will be nice to describe the Dropwizard vision of future place of Metrics library in Java world. It is important especially for Guys which do not use Dropwizard framework, but use only Metrics. The answer is important to make decision about choosing the monitoring library which will be right for a long distance.

A few year ago, this question was not actual, because Metrics was an independent library outside Dropwizard framework. But now when Metrics is tightly coupled with Dropwizard framework, it is time to worry. [This pull request](https://github.com/dropwizard/metrics/pull/1018) can be good example to describe the fears of community. If Metrics library is positioned just a part of Dropwizard, then this(and similar) request can be easy discarded, because of Dropwizard should not spend its time to solve problems with non target environments, the Dropwizard by itself has no problems with creating of new thread, and all who using Metrics in restricted environment should solve the problem by itself.

But, if Dropwizard see the future of Metrics as library number one for monitoring(including usage of Metrics without Dropwizard framework), then community should not worry, and Metrics users the right to expect that library will allow to customize key functionality.

**Comment by marshallpierce** [comment]
I do not care for Dropwizard, and I have no intent of making Metrics more Dropwizard focused. Quite the opposite, really: I want Metrics to be a fully independent thing (even if it happens to live inside the Dropwizard GitHub org).

**Comment by vladimir-bukhtoyarov** [comment]
Thanks
